lqr_pid_trajectory_tracking_node:
  ros__parameters:
    vehicle_ref_v: 2.0 # m/s // 只有在纯跟踪的时候才有用，和规划器联通后，车辆的w期望速度来自规划器
    vehicle_steering_ratio_double: 22.0 # ok

    lqr_pid_working_mode: 1 # 1: carla simulation 2: nezha vehicle. 3: matrix vehicle

    lqr_pid_with_planner_flag: 1   # lqr_pid做全局纯跟踪还是与规划算法上下贯通的标志 为 0 做纯跟踪，为 1 与规划算法上下贯通 #TODO:

    goal_tolerance : 0.5
    speed_P : 0.4
    speed_I : 0.02
    speed_D : 0.01

    lqr_controller_u : 10.0
    lqr_controller_cost_q_1 : 2.0
    lqr_controller_cost_q_2 : 1.0
    lqr_controller_cost_q_3 : 0.1
    lqr_controller_cost_q_4 : 0.1
