#0x183
int64 speed                #电机转速0-1
int64 angle                #实时转角2-3
int64 fault_msg            #故障代码4-5
int64 battery_capacity     #电池容量6
int64 drive_temperature1   #驱动器温度7

#0x283
int64 drive_temperature2   #驱动器温度0
int64 drive_current        #驱动器电流1-2
int64 sec                  #预留小时计秒位3
int64 minute               #预留小时计分位4
int64 hour                 #预留小时计时位5


int64 drive_temperature   #驱动器温度
